# Explore The "afppgecg" From PulseLM

- af: 
- ppg:
- ecg: electrocardiogram measures the heart rate.

In [1]:
import os
import sys

import pandas as pd

from tqdm import tqdm

# Get the current working directory of the notebook
notebook_dir = os.getcwd()

# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../custom_utils'))

from data_processing import DataProcessing

/Users/detraviousjamaribrinkley/Documents/Development/research_labs/roeh_labs/health/closed_loop_wearable_therapies/PulseLM/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
pd.set_option('max_colwidth', 800)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

## Load Data

In [3]:
df = datasets = DataProcessing.load_pulselm_datasets(notebook_dir, 'afppgecg')
df

,signal,text,qa
0,"[0.031112078577280045, 0.011500697582960129, -0.012881374917924404, -0.04621298983693123, -0.09158626198768616, -0.1506464034318924, -0.22341448068618774, -0.3083082437515259, -0.40234825015068054, -0.5015133023262024, -0.6011916399002075, -0.6966662406921387, -0.7835745811462402, -0.8582909107208252, -0.918196976184845, -0.9618212580680847, -0.9888465404510498, -1.0, -0.9968519806861877, -0.9815579056739807, -0.956579864025116, -0.9244218468666077, -0.887406051158905, -0.8475106358528137, -0.8062801361083984, -0.7648094892501831, -0.723794162273407, -0.6836289763450623, -0.6445317268371582, -0.6066648960113525, -0.5702304244041443, -0.5355190634727478, -0.5029077529907227, -0.4728098213672638, -0.44559425115585327, -0.4214977025985718, -0.4005535840988159, -0.3825579285621643, -0.3670...","A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Is atrial fibrillation present in this recording?"", ""answer"": ""non_af""}}"
1,"[-0.021528465673327446, -0.010177332907915115, 0.0011612351518124342, 0.012568795122206211, 0.024076586589217186, 0.035650044679641724, 0.04718397185206413, 0.0585063174366951, 0.06938853859901428, 0.07956160604953766, 0.08873704820871353, 0.09663254022598267, 0.10299984365701675, 0.10765182226896286, 0.11048456281423569, 0.11149198561906815, 0.11077260971069336, 0.10853058099746704, 0.10507354140281677, 0.10080775618553162, 0.09622860699892044, 0.09190290421247482, 0.0884397029876709, 0.08644811064004898, 0.08648304641246796, 0.08898331969976425, 0.09420961886644363, 0.10219214111566544, 0.1126977950334549, 0.1252247542142868, 0.13902904093265533, 0.15318389236927032, 0.16666829586029053, 0.17847514152526855, 0.18772460520267487, 0.19376519322395325, 0.19624599814414978, 0.19514857232...","A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Is atrial fibrillation present in this recording?"", ""answer"": ""non_af""}}"
2,"[0.040828511118888855, 0.0517774373292923, 0.06241843104362488, 0.07239484786987305, 0.08145906776189804, 0.08950825035572052, 0.09659764170646667, 0.10293114185333252, 0.10883042961359024, 0.1146860346198082, 0.12089522182941437, 0.127793088555336, 0.13558462262153625, 0.1442873328924179, 0.15369360148906708, 0.1633606255054474, 0.17263157665729523, 0.1806868612766266, 0.18661895394325256, 0.18952162563800812, 0.18858177959918976, 0.18316346406936646, 0.1728740781545639, 0.15760502219200134, 0.13754169642925262, 0.11314278095960617, 0.0850934237241745, 0.05424114689230919, 0.021525003015995026, -0.012092427350580692, -0.04568302258849144, -0.07839764654636383, -0.10949714481830597, -0.1383712887763977, -0.16454723477363586, -0.18768827617168427, -0.20758399367332458, -0.22413367033004...","A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Is this a normal rhythm or atrial fibrillation?"", ""answer"": ""non_af""}}"
3,"[-0.02589227631688118, -0.011456149630248547, 0.0028955386951565742, 0.017023516818881035, 0.030894530937075615, 0.04460116848349571, 0.05835102126002312, 0.07242847979068756, 0.08713659644126892, 0.102728471159935, 0.11933817714452744, 0.13692021369934082, 0.155205637216568, 0.1736825704574585, 0.1916073113679886, 0.20804964005947113, 0.22197052836418152, 0.2323247492313385, 0.23817534744739532, 0.23880425095558167, 0.2338017374277115, 0.22311970591545105, 0.20707879960536957, 0.18632692098617554, 0.16175620257854462, 0.13439235091209412, 0.10527505725622177, 0.07534832507371902, 0.04537693038582802, 0.01589975878596306, -0.012775682844221592, -0.0405404195189476, -0.06742164492607117, -0.09350399672985077, -0.11884912103414536, -0.14342708885669708, -0.16706962883472443, -0.189451515...","A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""What is the AF detection result for this segment?"", ""answer"": ""non_af""}}"
4,"[-0.08395710587501526, -0.1298823356628418, -0.17550820112228394, -0.22051261365413666, -0.26447978615760803, -0.3068942725658417, -0.3471623659133911, -0.3846539556980133, -0.41875600814819336, -0.4489280581474304, -0.47474992275238037, -0.4959549903869629, -0.5124431252479553, -0.524273693561554, -0.5316397547721863, -0.5348314046859741, -0.5341947078704834, -0.5300951600074768, -0.5228917002677917, -0.512924313545227, -0.500515341758728, -0.48598024249076843, -0.4696417450904846, -0.4518396556377411, -0.43293264508247375, -0.41328898072242737, -0.39326903223991394, -0.37320321798324585, -0.3533700704574585, -0.33397766947746277, -0.31515058875083923, -0.2969224154949188, -0.27923527359962463, -0.26194632053375244, -0.24484257400035858, -0.22766393423080444, -0.2101328819990158, -0.1...","A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Assess whether atrial fibrillation is present in this PPG."", ""answer"": ""non_af""}}"
...,...,...,...
64720,"[0.02009747549891472, 0.02457313984632492, 0.029076842591166496, 0.03362247720360756, 0.03819800168275833, 0.04276030510663986, 0.04723557457327843, 0.05152502283453941, 0.05551473796367645, 0.059087902307510376, 0.06213723495602608, 0.06457556039094925, 0.0663430392742157, 0.0674099251627922, 0.06777472794055939, 0.06745796650648117, 0.06649254262447357, 0.06491217017173767, 0.06274011731147766, 0.05998095124959946, 0.0566180981695652, 0.052619241178035736, 0.04795005917549133, 0.042594291269779205, 0.03657594323158264, 0.029977796599268913, 0.022950507700443268, 0.0157084371894598, 0.008511615917086601, 0.0016368175856769085, -0.004656389355659485, -0.010157685726881027, -0.014729986898601055, -0.01832152158021927, -0.020964983850717545, -0.02276526391506195, -0.023879094049334526, -...","A 38-year-old male patient. BMI 29.5. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Does this waveform indicate AF?"", ""answer"": ""non_af""}}"
64721,"[-0.005644588731229305, -0.006291037425398827, -0.006930799689143896, -0.0075591737404465675, -0.008169085718691349, -0.008751451969146729, -0.009296334348618984, -0.009794364683330059, -0.010237984359264374, -0.010622203350067139, -0.01094477716833353, -0.011205924674868584, -0.011407941579818726, -0.011555017903447151, -0.011653423309326172, -0.011711942963302135, -0.01174229010939598, -0.011759249493479729, -0.01178041473031044, -0.011825479567050934, -0.011915137059986591, -0.012069622986018658, -0.012306922115385532, -0.012640739791095257, -0.01307835802435875, -0.01361856795847416, -0.01424980815500021, -0.014948653057217598, -0.01567894220352173, -0.016392027959227562, -0.01702881045639515, -0.0175241157412529, -0.017813699319958687, -0.017843477427959442, -0.01757979951798916, ...","A 38-year-old male patient. BMI 29.5. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Does this waveform indicate AF?"", ""answer"": ""non_af""}}"
64722,"[0.0008597112027928233, 0.001839932519942522, 0.002780007664114237, 0.003641277551651001, 0.0043884702026844025, 0.004991824273020029, 0.005429512821137905, 0.005690070800483227, 0.005774331744760275, 0.005696353502571583, 0.005482885986566544, 0.005171159282326698, 0.004805042874068022, 0.0044300006702542305, 0.004087574779987335, 0.0038103554397821426, 0.0036183588672429323, 0.0035174794029444456, 0.003500231308862567, 0.0035485192202031612, 0.0036377948708832264, 0.0037417616695165634, 0.003836780320852995, 0.0039052744396030903, 0.003937677014619112, 0.003932754043489695, 0.003896400798112154, 0.00383927533403039, 0.003773809177801013, 0.0037112298887223005, 0.0036591768730431795, 0.00362032069824636, 0.0035921481903642416, 0.0035678353160619736, 0.0035379270557314157, 0.0034924377...","A 38-year-old male patient. BMI 29.5. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Does this waveform indicate AF?"", ""answer"": ""non_af""}}"
64723,"[0.0009960188763216138, 0.0009177027968689799, 0.0010175653733313084, 0.0014574776869267225, 0.0023528868332505226, 0.0037576707545667887, 0.0056565203703939915, 0.007965258322656155, 0.010538826696574688, 0.013185988180339336, 0.015689093619585037, 0.017826778814196587, 0.019397076219320297, 0.02023838832974434, 0.020246077328920364, 0.019382895901799202, 0.01768232136964798, 0.01524464413523674, 0.012226547114551067, 0.008825595490634441, 0.005261589307337999, 0.0017569211777299643, -0.0014819962671026587, -0.004280503373593092, -0.00650741858407855, -0.008081984706223011, -0.00897581409662962, -0.009210044518113136, -0.008848358877003193, -0.007986820302903652, -0.006741775665432215, -0.005237183533608913, -0.0035927952267229557, -0.001914447289891541, -0.00028748615295626223, 0.001...","A 38-year-old male patient. BMI 29.5. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Assess whether atrial fibrillation is present in this PPG."", ""answer"": ""non_af""}}"
64724,"[0.020901482552289963, 0.028547635301947594, 0.0355873629450798, 0.04150418937206268, 0.04594116657972336, 0.0487409383058548, 0.049946777522563934, 0.04976377636194229, 0.04848676919937134, 0.04640850052237511, 0.04372650384902954, 0.04046890512108803, 0.036457061767578125, 0.03131607547402382, 0.024534499272704124, 0.015564207918941975, 0.0039425622671842575, -0.01058604009449482, -0.02797313779592514, -0.047814249992370605, -0.06935519725084305, -0.09155924618244171, -0.11322543770074844, -0.13313758373260498, -0.1502167135477066, -0.16364996135234833, -0.1729748696088791, -0.17810837924480438, -0.17932139337062836, -0.1771690845489502, -0.17239315807819366, -0.165814608335495, -0.15823322534561157, -0.15034693479537964, -0.14269807934761047, -0.13564887642860413, -0.129383668303489...","A 38-year-old male patient. BMI 29.5. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Is atrial fibrillation present in this recording?"", ""answer"": ""non_af""}}"

## Explore Data

### Group By 'text' Column

- **What:** Count the occurrences of each patient/recording description
- **Why:** Understand the distribution of your dataset (e.g., how many recordings per patient type, AF vs non-AF cases, etc.).

In [4]:
df.groupby('text').size()

text
A 38-year-old male patient. BMI 29.5. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.      17535
A 48-year-old male patient. BMI 24.7. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.      17438
A 62-year-old female patient. BMI 25.6. wearable smartwatch PPG recording. atrial fibrillation (AF) detected.               1263
A 62-year-old female patient. BMI 25.6. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.    15540
A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.    12949
dtype: int64

In [5]:
df.groupby('text').first()  # Shows one example from each group

,signal,qa
text,,
"A 38-year-old male patient. BMI 29.5. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","[0.01255409512668848, 0.012033339589834213, 0.01155973318964243, 0.011170635931193829, 0.010886309668421745, 0.010708626359701157, 0.010623636655509472, 0.010606403462588787, 0.01062666717916727, 0.01065419614315033, 0.010663081891834736, 0.010634547099471092, 0.010558207519352436, 0.010431922040879726, 0.01026055496186018, 0.010054036043584347, 0.009825124405324459, 0.009587215259671211, 0.009352476336061954, 0.009130504913628101, 0.008927576243877411, 0.008746488019824028, 0.00858690869063139, 0.00844608899205923, 0.008319750428199768, 0.00820300355553627, 0.008091139607131481, 0.007980228401720524, 0.007867454551160336, 0.0077512264251708984, 0.007631067652255297, 0.007507385686039925, 0.007381164003163576, 0.007253651507198811, 0.007126096170395613, 0.006999551318585873, 0.00687475...","{""af_label"": {""question"": ""What is the AF label for this PPG recording?"", ""answer"": ""non_af""}}"
"A 48-year-old male patient. BMI 24.7. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","[-0.1815912276506424, -0.18271327018737793, -0.18377530574798584, -0.1846984624862671, -0.18542148172855377, -0.1859075427055359, -0.18614542484283447, -0.18614524602890015, -0.18593062460422516, -0.18553008139133453, -0.18496990203857422, -0.1842697262763977, -0.18344110250473022, -0.1824885457754135, -0.1814117133617401, -0.18020771443843842, -0.17887257039546967, -0.1774018555879593, -0.1757909506559372, -0.1740349978208542, -0.17212821543216705, -0.1700616478919983, -0.16781938076019287, -0.16537417471408844, -0.16268429160118103, -0.15969353914260864, -0.15633516013622284, -0.15254011750221252, -0.1482481062412262, -0.14341899752616882, -0.1380416452884674, -0.13213756680488586, -0.12575891613960266, -0.11898159980773926, -0.11189540475606918, -0.10459316521883011, -0.097160920500...","{""af_label"": {""question"": ""Classify this PPG as AF or non-AF."", ""answer"": ""non_af""}}"
A 62-year-old female patient. BMI 25.6. wearable smartwatch PPG recording. atrial fibrillation (AF) detected.,"[0.014684510417282581, 0.011001652106642723, 0.006944605614989996, 0.002088973531499505, -0.003875746624544263, -0.011102174408733845, -0.019559785723686218, -0.029034974053502083, -0.03915872424840927, -0.04945731908082962, -0.0594148263335228, -0.06853310018777847, -0.07637717574834824, -0.082600899040699, -0.08695577830076218, -0.08929125219583511, -0.0895552709698677, -0.08779998123645782, -0.08419101685285568, -0.0790134146809578, -0.07266503572463989, -0.06562980264425278, -0.058428969234228134, -0.05155579745769501, -0.045406125485897064, -0.040220629423856735, -0.03605278208851814, -0.03276980295777321, -0.030084801837801933, -0.027610909193754196, -0.02492496557533741, -0.021629486232995987, -0.01740465871989727, -0.012045321054756641, -0.005480105523020029, 0.0022284770384430...","{""af_label"": {""question"": ""Does this PPG signal show atrial fibrillation?"", ""answer"": ""af""}}"
"A 62-year-old female patient. BMI 25.6. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","[0.031069546937942505, 0.040314048528671265, 0.049214985221624374, 0.057397905737161636, 0.06454577296972275, 0.07041601091623306, 0.07484500855207443, 0.07774290442466736, 0.07908251136541367, 0.07888562232255936, 0.07720917463302612, 0.07413265854120255, 0.0697479099035263, 0.06415211409330368, 0.05744364857673645, 0.049719057977199554, 0.041068483144044876, 0.031567759811878204, 0.021268101409077644, 0.010187310166656971, -0.0016921453643590212, -0.014414343051612377, -0.028029559180140495, -0.04256507381796837, -0.05799275264143944, -0.07420078665018082, -0.09097691625356674, -0.10800859332084656, -0.12490200996398926, -0.1412176787853241, -0.15651658177375793, -0.17040874063968658, -0.18259567022323608, -0.1928996443748474, -0.20127566158771515, -0.2078053206205368, -0.21267430484...","{""af_label"": {""question"": ""Assess whether atrial fibrillation is present in this PPG."", ""answer"": ""non_af""}}"
"A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","[0.031112078577280045, 0.011500697582960129, -0.012881374917924404, -0.04621298983693123, -0.09158626198768616, -0.1506464034318924, -0.22341448068618774, -0.3083082437515259, -0.40234825015068054, -0.5015133023262024, -0.6011916399002075, -0.6966662406921387, -0.7835745811462402, -0.8582909107208252, -0.918196976184845, -0.9618212580680847, -0.9888465404510498, -1.0, -0.9968519806861877, -0.9815579056739807, -0.956579864025116, -0.9244218468666077, -0.887406051158905, -0.8475106358528137, -0.8062801361083984, -0.7648094892501831, -0.723794162273407, -0.6836289763450623, -0.6445317268371582, -0.6066648960113525, -0.5702304244041443, -0.5355190634727478, -0.5029077529907227, -0.4728098213672638, -0.44559425115585327, -0.4214977025985718, -0.4005535840988159, -0.3825579285621643, -0.3670...","{""af_label"": {""question"": ""Is atrial fibrillation present in this recording?"", ""answer"": ""non_af""}}"

In [6]:
# Create unique patient identifier based on age, gender, BMI
df['patient_id'] = df.groupby(['text']).ngroup().add(1).apply(lambda x: f'P{x}')

# Or more explicitly extract features:
import re

def extract_patient_info(text):
    age = re.search(r'(\d+)-year-old', text).group(1)
    gender = re.search(r'(male|female) patient', text).group(1)
    bmi = re.search(r'BMI (\d+\.\d+)', text).group(1)
    return f"{age}_{gender}_{bmi}"

df['patient_key'] = df['text'].apply(extract_patient_info)
df['patient_id'] = pd.factorize(df['patient_key'])[0] + 1
df['patient_id'] = df['patient_id'].apply(lambda x: f'P{x}')

df.groupby(['patient_id', 'text']).size()

patient_id  text
P1          A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.    12949
P2          A 48-year-old male patient. BMI 24.7. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.      17438
P3          A 62-year-old female patient. BMI 25.6. wearable smartwatch PPG recording. atrial fibrillation (AF) detected.               1263
            A 62-year-old female patient. BMI 25.6. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.    15540
P4          A 38-year-old male patient. BMI 29.5. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.      17535
dtype: int64

### Look into specific patient

In [7]:
filt_patient = (df['patient_id'] == 'P1')
patient_df = df[filt_patient]
patient_df

,signal,text,qa,patient_id,patient_key
0,"[0.031112078577280045, 0.011500697582960129, -0.012881374917924404, -0.04621298983693123, -0.09158626198768616, -0.1506464034318924, -0.22341448068618774, -0.3083082437515259, -0.40234825015068054, -0.5015133023262024, -0.6011916399002075, -0.6966662406921387, -0.7835745811462402, -0.8582909107208252, -0.918196976184845, -0.9618212580680847, -0.9888465404510498, -1.0, -0.9968519806861877, -0.9815579056739807, -0.956579864025116, -0.9244218468666077, -0.887406051158905, -0.8475106358528137, -0.8062801361083984, -0.7648094892501831, -0.723794162273407, -0.6836289763450623, -0.6445317268371582, -0.6066648960113525, -0.5702304244041443, -0.5355190634727478, -0.5029077529907227, -0.4728098213672638, -0.44559425115585327, -0.4214977025985718, -0.4005535840988159, -0.3825579285621643, -0.3670...","A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Is atrial fibrillation present in this recording?"", ""answer"": ""non_af""}}",P1,64_female_27.9
1,"[-0.021528465673327446, -0.010177332907915115, 0.0011612351518124342, 0.012568795122206211, 0.024076586589217186, 0.035650044679641724, 0.04718397185206413, 0.0585063174366951, 0.06938853859901428, 0.07956160604953766, 0.08873704820871353, 0.09663254022598267, 0.10299984365701675, 0.10765182226896286, 0.11048456281423569, 0.11149198561906815, 0.11077260971069336, 0.10853058099746704, 0.10507354140281677, 0.10080775618553162, 0.09622860699892044, 0.09190290421247482, 0.0884397029876709, 0.08644811064004898, 0.08648304641246796, 0.08898331969976425, 0.09420961886644363, 0.10219214111566544, 0.1126977950334549, 0.1252247542142868, 0.13902904093265533, 0.15318389236927032, 0.16666829586029053, 0.17847514152526855, 0.18772460520267487, 0.19376519322395325, 0.19624599814414978, 0.19514857232...","A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Is atrial fibrillation present in this recording?"", ""answer"": ""non_af""}}",P1,64_female_27.9
2,"[0.040828511118888855, 0.0517774373292923, 0.06241843104362488, 0.07239484786987305, 0.08145906776189804, 0.08950825035572052, 0.09659764170646667, 0.10293114185333252, 0.10883042961359024, 0.1146860346198082, 0.12089522182941437, 0.127793088555336, 0.13558462262153625, 0.1442873328924179, 0.15369360148906708, 0.1633606255054474, 0.17263157665729523, 0.1806868612766266, 0.18661895394325256, 0.18952162563800812, 0.18858177959918976, 0.18316346406936646, 0.1728740781545639, 0.15760502219200134, 0.13754169642925262, 0.11314278095960617, 0.0850934237241745, 0.05424114689230919, 0.021525003015995026, -0.012092427350580692, -0.04568302258849144, -0.07839764654636383, -0.10949714481830597, -0.1383712887763977, -0.16454723477363586, -0.18768827617168427, -0.20758399367332458, -0.22413367033004...","A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Is this a normal rhythm or atrial fibrillation?"", ""answer"": ""non_af""}}",P1,64_female_27.9
3,"[-0.02589227631688118, -0.011456149630248547, 0.0028955386951565742, 0.017023516818881035, 0.030894530937075615, 0.04460116848349571, 0.05835102126002312, 0.07242847979068756, 0.08713659644126892, 0.102728471159935, 0.11933817714452744, 0.13692021369934082, 0.155205637216568, 0.1736825704574585, 0.1916073113679886, 0.20804964005947113, 0.22197052836418152, 0.2323247492313385, 0.23817534744739532, 0.23880425095558167, 0.2338017374277115, 0.22311970591545105, 0.20707879960536957, 0.18632692098617554, 0.16175620257854462, 0.13439235091209412, 0.10527505725622177, 0.07534832507371902, 0.04537693038582802, 0.01589975878596306, -0.012775682844221592, -0.0405404195189476, -0.06742164492607117, -0.09350399672985077, -0.11884912103414536, -0.14342708885669708, -0.16706962883472443, -0.189451515...","A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""What is the AF detection result for this segment?"", ""answer"": ""non_af""}}",P1,64_female_27.9
4,"[-0.08395710587501526, -0.1298823356628418, -0.17550820112228394, -0.22051261365413666, -0.26447978615760803, -0.3068942725658417, -0.3471623659133911, -0.3846539556980133, -0.41875600814819336, -0.4489280581474304, -0.47474992275238037, -0.4959549903869629, -0.5124431252479553, -0.524273693561554, -0.5316397547721863, -0.5348314046859741, -0.5341947078704834, -0.5300951600074768, -0.5228917002677917, -0.512924313545227, -0.500515341758728, -0.48598024249076843, -0.4696417450904846, -0.4518396556377411, -0.43293264508247375, -0.41328898072242737, -0.39326903223991394, -0.37320321798324585, -0.3533700704574585, -0.33397766947746277, -0.31515058875083923, -0.2969224154949188, -0.27923527359962463, -0.26194632053375244, -0.24484257400035858, -0.22766393423080444, -0.2101328819990158, -0.1...","A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Assess whether atrial fibrillation is present in this PPG."", ""answer"": ""non_af""}}",P1,64_female_27.9
...,...,...,...,...,...
12944,"[-0.03806198760867119, -0.03329853713512421, -0.028750063851475716, -0.024635186418890953, -0.021064627915620804, -0.018022799864411354, -0.015373156405985355, -0.012881757691502571, -0.010252086445689201, -0.007163975387811661, -0.0033101513981819153, 0.001574945286847651, 0.007697619963437319, 0.015199308283627033, 0.024160116910934448, 0.03460628166794777, 0.046515870839357376, 0.05981873720884323, 0.07438942044973373, 0.09003475308418274, 0.10648015886545181, 0.12335991114377975, 0.1402166783809662, 0.15651394426822662, 0.1716628074645996, 0.185061514377594, 0.19614377617835999, 0.2044292539358139, 0.20956876873970032, 0.21137644350528717, 0.20984312891960144, 0.2051287442445755, 0.19753505289554596, 0.18746374547481537, 0.17536723613739014, 0.16170047223567963, 0.14688068628311157...","A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Is this a normal rhythm or atrial fibrillation?"", ""answer"": ""non_af""}}",P1,64_female_27.9
12945,"[0.053090594708919525, 0.05248090252280235, 0.05178089812397957, 0.05098415166139603, 0.050076644867658615, 0.04904071241617203, 0.04786242917180061, 0.04653935506939888, 0.045086465775966644, 0.043539151549339294, 0.04195269197225571, 0.0403980053961277, 0.03895396366715431, 0.03769741207361221, 0.03669263795018196, 0.03598221763968468, 0.03558112680912018, 0.0354754738509655, 0.03562651202082634, 0.035979464650154114, 0.036475520581007004, 0.03706475347280502, 0.03771770000457764, 0.03843407332897186, 0.039248086512088776, 0.040230464190244675, 0.041487470269203186, 0.04315704107284546, 0.04540169611573219, 0.04839788004755974, 0.052321456372737885, 0.05732943117618561, 0.06353850662708282, 0.07100167125463486, 0.07968491315841675, 0.08944720774888992, 0.10002761334180832, 0.11104356...","A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Is this a normal rhythm or atrial fibrillation?"", ""answer"": ""non_af""}}",P1,64_female_27.9
12946,"[0.1932096779346466, 0.2321532815694809, 0.2691081166267395, 0.3021716773509979, 0.32987526059150696, 0.35132670402526855, 0.3662761151790619, 0.37510204315185547, 0.378726065158844, 0.3784700036048889, 0.37587636709213257, 0.3725143074989319, 0.3697932958602905, 0.36880525946617126, 0.37021148204803467, 0.37418580055236816, 0.3804181218147278, 0.38817599415779114, 0.3964136242866516, 0.4039132297039032, 0.40943917632102966, 0.41188597679138184, 0.4104038178920746, 0.4044894874095917, 0.39403635263442993, 0.3793417513370514, 0.3610738217830658, 0.3402021825313568, 0.3178989589214325, 0.2954168915748596, 0.27395525574684143, 0.2545246481895447, 0.237824946641922, 0.22415179014205933, 0.21334457397460938, 0.20478688180446625, 0.1974639892578125, 0.19007563591003418, 0.18119506537914276, ...","A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Assess whether atrial fibrillation is present in this PPG."", ""answer"": ""non_af""}}",P1,64_female_27.9
12947,"[0.07247991114854813, 0.07349486649036407, 0.07438302785158157, 0.07506386935710907, 0.07547666132450104, 0.07558836787939072, 0.07539906352758408, 0.0749436765909195, 0.0742889940738678, 0.07352586835622787, 0.07275722920894623, 0.07208391278982162, 0.07159072905778885, 0.07133544236421585, 0.07134220749139786, 0.07160049676895142, 0.07206908613443375, 0.07268428802490234, 0.07337068766355515, 0.07405292242765427, 0.07466651499271393, 0.07516643404960632, 0.07553225755691528, 0.07576927542686462, 0.07590567320585251, 0.07598616182804108, 0.07606330513954163, 0.07618778944015503, 0.07639950513839722, 0.07672083377838135, 0.07715357095003128, 0.0776795744895935, 0.07826479524374008, 0.0788651704788208, 0.07943286001682281, 0.079921193420887, 0.08028758317232132, 0.08049415796995163, 0.0...","A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""What is the AF detection result for this segment?"", ""answer"": ""non_af""}}",P1,64_female_27.9
12948,"[0.006157315336167812, 0.0053561776876449585, 0.004570061340928078, 0.003819604404270649, 0.0031318606343120337, 0.0025398090947419405, 0.0020787501707673073, 0.0017804942326620221, 0.001666946685872972, 0.0017447808058932424, 0.0020024641416966915, 0.002410248387604952, 0.002923070453107357, 0.0034857895225286484, 0.0040398468263447285, 0.004530297592282295, 0.004912184085696936, 0.005155377089977264, 0.005247271154075861, 0.005193051416426897, 0.005013611633330584, 0.004741563927382231, 0.0044160569086670876, 0.004077265039086342, 0.003761372296139598, 0.0034966878592967987, 0.0033013003412634134, 0.003182429587468505, 0.003137398511171341, 0.0031558782793581486, 0.0032228552736341953, 0.0033216734882444143, 0.003436579369008541, 0.0035544191487133503, 0.003665399271994829, 0.0037630...","A 64-year-old female patient. BMI 27.9. wearable smartwatch PPG recording. normal sinus rhythm, no atrial fibrillation.","{""af_label"": {""question"": ""Is atrial fibrillation present in this recording?"", ""answer"": ""non_af""}}",P1,64_female_27.9